### ISSUE TITLE
Proposal: Use docparser for parsing

### ISSUE THREAD

**Issue by eudoxia0** [quickdocs/quickdocs#36]
I wrote [this](https://github.com/eudoxia0/docparser). It uses the same technique as the Quickdocs parser to extract documentation (Hooking into macroexpansion).

It extracts as much documentation as Quickdocs, and additionally documents conditions, as well as every CFFI construct, which is useful for documenting foreign library APIs.

It ignores things like foreign library errors, so you can generate documentation without installing foreign libraries, which would solve issues people have been having with Quickdocs for a while (See #33, #29, #28, #26).

It does not, however, fix #24.

**Comment by fukamachi** [comment]
Thank you for the suggestion.

I tried docparser and found it's cool!
I forked it to [quickdocs-parser](https://github.com/quickdocs/quickdocs-parser) for the next generation of Quickdocs.

### Difference of the forked version

#### 1. No dependencies

If it depends on other libraries, it cannot be used for those dependencies.

#### 2. Project name

Because the parser must have a unique name which isn't used in any Quicklisp libraries to parse all libraries including `docparser`.

**Comment by eudoxia0** [comment]
Glad to hear you liked it! One question though, I noticed you moved this and Lack to CircleCI. Is this due to the higher memory ceiling or why?

**Comment by fukamachi** [comment]
> I noticed you moved this and Lack to CircleCI. Is this due to the higher memory ceiling or why?

Just because it's faster. Travis CI is unbearably slow these days.

**Comment by fukamachi** [comment]
Done.
